#!/usr/bin/python3

import argparse
import re
import json
import sys

def parse_arguments():
    parser = argparse.ArgumentParser(description='Loads json, outputs md')
    parser.add_argument('-f', '--file', help='file to load', required=True)
    return parser.parse_args()

def main():
    args = parse_arguments()
    headerfile = args.file.replace('.json', '.header')
    with open(headerfile) as f:
        print(f.read())
    counter = 1
    with open(args.file) as f:
        data = json.load(f)
        for item in data:
            if 'urls' in item:
                output = '### #' + str(counter) + ' [' + item['name'] + ']('+ item['urls'][0][1] + ')'
                for url in item['urls']:
                    output = output + ' [[' + url[0] + '](' + url[1] + ')]'
            else:
                output = '### #' + str(counter) + ' ' + item['name']
            if 'price' in item:
                output = output + ': ' + item['price']
            print(output)
            counter += 1
            if 'Positives' in item:
                print('- Positives: ' + item['Positives'])
            if 'Negatives' in item:
                print('- Negatives: ' + item['Negatives'])
            if 'Setup' in item:
                print('- Setup: ' + item['Setup'])
            if 'attributes' in item:
                for attribute in item['attributes']:
                    print('- ' + attribute + ': ' + item['attributes'][attribute])
            if 'comparisons' in item:
                print('- Comparisons and Sound Samples')
                for comparison in item['comparisons']:
                    if comparison[0]:
                        print('    - [' + comparison[0] + '](' + comparison[1] + ')')
                    else:
                        print('    - <' + comparison[1] + '>')
            if 'links' in item:
                print('- Links')
                for link in item['links']:
                    if link[0]:
                        print('    - [' + link[0] + '](' + link[1] + ')')
                    else:
                        print('    - <' + link[1] + '>')
                        
            print('')
            

    try:
        footerfile = args.file.replace('.json', '.footer')
        with open(footerfile) as f:
            print(f.read())
    except:
        with open('global.footer') as f:
            print(f.read())
        

if __name__ == "__main__":
    main()

