#!/usr/bin/python3

import argparse
import re
import json
import sys

def parse_arguments():
    parser = argparse.ArgumentParser(description='Loads file, outputs json')
    parser.add_argument('-f', '--file', help='file to load', required=True)
    return parser.parse_args()

def main():
    jsonOut = []
    speaker = {}
    urlRe = r'\[(.+)\]\(([^)]+)\)'
    args = parse_arguments()
    toPut = ''
    with open(args.file) as f:
        line = f.readline()
        while line:
            if line.startswith('###'):
                if '[' in line:
                    name = line.split('[')[1].split(']')[0]
                    if ': ' in line:
                        price = line.split(':')[-1].strip()
                    else:
                        price = ''
                else:
                    name = ' '.join(line.split(' ')[2:]).split(':')[0].strip()
                    if ': ' in line:
                        price = line.split(':')[1].strip()
                    else:
                        price = ''
                urls = []
                for i in line.split('[[')[1:]:
                    if ']' in i:
                        sitename = i.split(']')[0]
                        siteurl = i.split('(')[1].split(')')[0]
                        urls.append([sitename, siteurl])
                if speaker:
                    jsonOut.append(speaker)
                speaker = { "name": name, "price": price, "attributes":{} }
                if urls:
                    speaker['urls'] = urls
            if line.startswith('- '):
                if '- Comparisons and Sound Samples' in line:
                    speaker['comparisons'] = []
                    line = f.readline()
                    while line.startswith('    - '):
                        if '<' in line:
                            name = ''
                            url = line.split('<')[1].split('>')[0]
                            speaker['comparisons'].append([name, url])
                        elif '[' in line:
                            match = re.search(urlRe, line)
                            #if match:
                            name = match.group(1)
                            url = match.group(2)
                            speaker['comparisons'].append([name, url])
                        else:
                            print('Error in : ' + line)
                            sys.exit(1)
                        line = f.readline()
                if '- Links' in line:
                    speaker['links'] = []
                    line = f.readline()
                    while line.startswith('    - '):
                        if '<' in line:
                            name = ''
                            url = line.split('<')[1].split('>')[0]
                            speaker['links'].append([name, url])
                        elif '[' in line:
                            match = re.search(urlRe, line)
                            #if match:
                            name = match.group(1)
                            url = match.group(2)
                            speaker['links'].append([name, url])
                        line = f.readline()
                elif '- Positives:' in line or '- Negatives:' in line:
                    attribute = line.split(':')[0].replace('- ','').strip()
                    atttributeValue = ':'.join(line.split(':')[1:]).strip()
                    speaker[attribute] = atttributeValue
                elif line.startswith('- '):
                    attribute = line.split(':')[0].replace('- ','').strip()
                    atttributeValue = ':'.join(line.split(':')[1:]).strip()
                    speaker['attributes'][attribute] = atttributeValue
            line = f.readline()
        if speaker:
            jsonOut.append(speaker)
    print(json.dumps(jsonOut, indent=4, sort_keys=True))


if __name__ == "__main__":
    main()

